### ISSUE TITLE
How to get the grid background in post content?

### ISSUE THREAD

**Issue by Jerwins** [qdzhang/hugo-notepadium-mod#2]
Hello :) 

In the original theme it has this notebook style grids in content. How do I add that to your theme? 

I like your modifications better than original but would like the above in mine.

For example: https://examplesite.lvv.me/post/markdown-syntax/ <-------- grid lines in this page content.

**Comment by qdzhang** [comment]
Hi!
You can add custom css to have notebook style grids easily with following steps:

1. Create a css file in assets/css directory of your site root (assume the new css file is named grids.css)
2. Put these styles in grids.css

```css
html {
 --grid-line-color:rgba(50,0,0,5%)
}
html[data-theme=dark] {
 --grid-line-color:rgba(250,200,200,5%)
}
.markdown-body {
 background-image:linear-gradient(90deg,var(--grid-line-color) 3%,transparent 3%),linear-gradient(360deg,var(--grid-line-color) 3%,transparent 3%);
 background-size:20px 20px;
 background-position:50%
}
```

3. In your hugo site config file (normally config.toml), declare the custom style you want to use:
```toml
[params.assets]
css = ["css/grids.css"]
```
Done. The post content background will have grids.

The theme is still work in progress, and it lacks documents. If something is not clear, [the configuration](https://github.com/qdzhang/littlezhang.com/blob/b73198a7472b5e38a9fd48e84a9133188b80ba1e/config.toml#L91) in my own site may be an example.

Feel free to ask questions or make suggestions.
